// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVE5rZB9g3fx22kODCvlq14uu9RU78MHo',
    appId: '1:662467480250:web:25d099407364e030ba5083',
    messagingSenderId: '662467480250',
    projectId: 'spotify-fe89e',
    authDomain: 'spotify-fe89e.firebaseapp.com',
    storageBucket: 'spotify-fe89e.firebasestorage.app',
    measurementId: 'G-VRT0XBFJTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0y469Lj-VE-zUnad-se3mFhglVRLIvYs',
    appId: '1:662467480250:android:eea1ee2de6ec541dba5083',
    messagingSenderId: '662467480250',
    projectId: 'spotify-fe89e',
    storageBucket: 'spotify-fe89e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMOBph5Qzvl6pNRLEz1zF654E0MwTzBoI',
    appId: '1:662467480250:ios:4ccdb30b41ac3d97ba5083',
    messagingSenderId: '662467480250',
    projectId: 'spotify-fe89e',
    storageBucket: 'spotify-fe89e.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );
}
